

{{ config(materialized='table') }}

WITH CUSTOMER AS (
  SELECT 
    C_CUSTKEY AS CUSTOMER_ID,
    C_NATIONKEY AS NATION_ID,
    C_NAME AS NAME,
    C_ADDRESS AS ADDRESS,
    C_PHONE AS PHONE_NUMBER,
    C_ACCTBAL AS ACCOUNT_BALANCE,
    C_MKTSEGMENT AS MARKET_SEGMENT,
    C_COMMENT AS COMMENT
  FROM {{ source('src', 'customer') }}
)
SELECT * FROM CUSTOMER
